services:
  postgres:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
      - backups:/var/lib/postresql/backups
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
